### ISSUE TITLE
css style

### ISSUE THREAD

**Issue by nagwan** [nagwan/resume#1]
when u check the html file, u will find the following part in the style section 
.box1{-webkit-transform: rotate(90deg);   
          -moz-transform: rotate(90deg);
          -ms-transform: rotate(90deg);
          -o-transform: rotate(90deg);
          transform: rotate(90deg);
           background-color: white;
           border: 2px dashed #E0E0E0;
           width: 11%;
           margin: auto;
           margin-top: 90;
           padding: 10px;
          font-family: cursive;
          text-align: center;
          float: right;}
    
    .box2{-webkit-transform: rotate(90deg);   
          -moz-transform: rotate(90deg);
          -ms-transform: rotate(90deg);
          -o-transform: rotate(90deg);
          transform: rotate(90deg);
          background-color: white;
          border: 2px dashed red;
          width: 11%;
          margin: auto;
          margin-top: 90;
          padding: 10px;
          font-family: cursive;
          text-align: center;
          float: right;}
    
    .box3{-webkit-transform: rotate(90deg);   
          -moz-transform: rotate(90deg);
          -ms-transform: rotate(90deg);
          -o-transform: rotate(90deg);
          transform: rotate(90deg);
          transform-origin: left 200;
          background-color: white;
          border: 2px dashed;
          border-color: black;
          width: 11%;
          margin: auto;
          margin-top: 90;
          padding: 10px;
          font-family: cursive;
          text-align: center;
         float: right;}   

everything goes in the right way except the color of the borders (for box2 and box3) what seems to be the problem??

**Comment by Nagwan** [comment]
@Hazem Ali
